### ISSUE TITLE
NullPointerException when running Android "Screenshot2"

### ISSUE THREAD

**Issue by mkm12789** [bitbar/opencv-library#5]
When stepping through the failing bitbar image recognition demo I notice I'm getting the following error when running the command line screenshot2 app for android:

Exception in thread "main" java.lang.NullPointerException
    at com.android.ddmlib.MonitorThread.wakeup(MonitorThread.java:453)
    at com.android.ddmlib.MonitorThread.quit(MonitorThread.java:461)
    at com.android.ddmlib.AndroidDebugBridge.terminate(AndroidDebugBridge.java:293)
    at com.android.screenshot.Screenshot.main(Screenshot.java:280)

I'm using version 26.1.1 of Android SDK tools and JDK 8u151

Has anyone experienced this?

**Comment by ShivaniThaman** [comment]
Same issue.. No solution

**Comment by adityabhargav** [comment]
Mee too facing same issue:: 

java.io.IOException: Cannot run program "screenshot2": error=2, No such file or directory

**Comment by szprutamich** [comment]
Do you have it in android-sdk/tools/bin/ ? If so it should be enough to add it to the PATH.
It can be also installed (for Ubuntu): 
sudo apt install android-platform-tools-base
